// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClM_2rcVorSJ4lHZnsdcEVJxHkC_CKnVg',
    appId: '1:701721676059:web:5cd751302af18ed44debbe',
    messagingSenderId: '701721676059',
    projectId: 'proyek-3-2b89c',
    authDomain: 'proyek-3-2b89c.firebaseapp.com',
    storageBucket: 'proyek-3-2b89c.firebasestorage.app',
    measurementId: 'G-QPJFXPQ2ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyKah6MI70fHdbiGMI2wis5GhHCyosNA',
    appId: '1:701721676059:android:e5129a0812df4d414debbe',
    messagingSenderId: '701721676059',
    projectId: 'proyek-3-2b89c',
    storageBucket: 'proyek-3-2b89c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGobAsdOR6XRI6uX48W-aUxy_rctyLAs',
    appId: '1:701721676059:ios:918c3e03c9bfda684debbe',
    messagingSenderId: '701721676059',
    projectId: 'proyek-3-2b89c',
    storageBucket: 'proyek-3-2b89c.firebasestorage.app',
    iosBundleId: 'com.example.proyek3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGobAsdOR6XRI6uX48W-aUxy_rctyLAs',
    appId: '1:701721676059:ios:918c3e03c9bfda684debbe',
    messagingSenderId: '701721676059',
    projectId: 'proyek-3-2b89c',
    storageBucket: 'proyek-3-2b89c.firebasestorage.app',
    iosBundleId: 'com.example.proyek3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClM_2rcVorSJ4lHZnsdcEVJxHkC_CKnVg',
    appId: '1:701721676059:web:72dfbbb3c78912794debbe',
    messagingSenderId: '701721676059',
    projectId: 'proyek-3-2b89c',
    authDomain: 'proyek-3-2b89c.firebaseapp.com',
    storageBucket: 'proyek-3-2b89c.firebasestorage.app',
    measurementId: 'G-NCH6EV6V76',
  );
}
